[kalix]
#version = 0.0.1

[inputs]
flow = flows.csv
 
[constants]
c.rfsum = 1

[node.inflow]
loc = 0,0
type = inflow
inflow = data.flow.by_name.flow
ds_1 = storage

[node.storage]
loc = 0,50
type = storage
dimensions = Level [m], Volume [ML], Area [km2], Spill [ML], 
             0        , 0          , 0         , 0, 
             5000     , 5000       , 1         , 0, 
             5001     , 5001       , 1         , 1, 
ds_1 = stream_1
ds_1_outlet = 0
ds_1_force_release = this.volume[-1,0] / 10
ds_2 = stream_2
ds_2_outlet = 100
ds_2_force_release = 100


[node.stream_1]
loc=0,100
type = gauge
ds_1 = unreg_user

[node.unreg_user]
loc = 0,150
type = unregulated_user
demand = 50

[node.stream_2]
loc = 100,100
type = gauge

[outputs]
node.inflow.inflow
node.storage.ds_1_outlet
node.storage.ds_1_spill
node.stream_1.usflow
node.stream_2.usflow
node.storage.volume
node.unreg_user.demand
node.unreg_user.diversion