
[kalix]
start = 2000-01-01
end = 2000-01-10

[constants]
c.x = 1 # range -4.5 to +4.5
c.y = 1 # range -4.5 to +4.5

# minimum value of beale function is f(x,y) = 0 when x=3, y=0.5

[inputs]

[node.my_node]
loc = 0,0
type = inflow
inflow = (1.5 - c.x + c.x*c.y)^2 + 
 (2.25 - c.x + c.x * c.y^2)^2 + 
 (2.625 - c.x + c.x * c.y^3)^2

[outputs]
node.my_node.ds_1

