[kalix]
start = 1980-01-01
end = 2009-12-31

[inputs]
data/us_flow.csv

[node.0001_in]
type = inflow
loc = -40, 0
inflow = data.us_flow_csv.by_index.1
ds_1 = 0002_sp

[node.0002_sp]
type = splitter
loc = -40, 40
table = 0        , 0, 
        2000     , 2000,         
        100000   , 2000,
ds_1 = 0004_high_flow
ds_2 = 0003_low_flow

[node.0003_low_flow]
type = loss
loc = -40, 80
table = 0, 0, 1e8, 1e8 #loses everything

[node.0004_high_flow]
type = loss
loc = -80, 80
table = 0, 0, 1e8, 1e8 #loses everything

#####################################################

[node.0011_in]
type = inflow
loc = 0, 0
inflow = data.us_flow_csv.by_index.1
ds_1 = 0012_sp

[node.0012_sp]
type = splitter
loc = 0, 40
table = 0        , 0, 
        2000     , 0,         
        100000   , 98000,
ds_1 = 0013_low_flow
ds_2 = 0014_high_flow

[node.0013_low_flow]
type = loss
loc = 0, 80
table = 0, 0, 1e8, 1e8 #loses everything

[node.0014_high_flow]
type = loss
loc = 40, 80
table = 0, 0, 1e8, 1e8 #loses everything


########################################################

[outputs]
node.0001_in.ds_1
node.0002_sp.ds_1
node.0002_sp.ds_2
node.0003_low_flow.usflow
node.0004_high_flow.usflow

node.0011_in.ds_1
node.0012_sp.ds_1
node.0012_sp.ds_2
node.0013_low_flow.usflow
node.0014_high_flow.usflow
