package com.kalix.ide.windows.optimisation;

import com.kalix.ide.managers.optimisation.OptimisationConfigModel.ParamEntry;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link ParametersConfigPanel#buildAutoGeneratedEntries(List)} — the
 * path that fills in the parameters table when kalixcli reports a model's optimisable
 * parameters.
 *
 * <p>Only the static factory is exercised; it is a pure function of the parameter-name
 * list and needs no Swing widgets, so these tests run headless.</p>
 */
class ParametersConfigPanelTest {

    @Test
    @DisplayName("A null parameter list yields no entries")
    void testNullYieldsEmpty() {
        assertTrue(ParametersConfigPanel.buildAutoGeneratedEntries(null).isEmpty());
    }

    @Test
    @DisplayName("An empty parameter list yields no entries")
    void testEmptyYieldsEmpty() {
        assertTrue(ParametersConfigPanel.buildAutoGeneratedEntries(List.of()).isEmpty());
    }

    @Test
    @DisplayName("Every reported parameter gets a row, in the order reported")
    void testAllParametersPresentInOrder() {
        List<String> names = List.of(
                "node.g1.x1", "node.unknown.mystery", "const.scale", "node.r1.nlm_k");
        List<ParamEntry> entries = ParametersConfigPanel.buildAutoGeneratedEntries(names);

        assertEquals(names.size(), entries.size());
        for (int i = 0; i < names.size(); i++) {
            assertEquals(names.get(i), entries.get(i).name);
        }
    }

    @Test
    @DisplayName("Gene indices are allocated sequentially from 1")
    void testGeneIndicesAreSequential() {
        List<ParamEntry> entries = ParametersConfigPanel.buildAutoGeneratedEntries(
                List.of("node.g1.x1", "node.g1.x2", "node.g1.x3"));

        assertEquals("lin_range(g(1),1,1500)", entries.get(0).expression);
        assertEquals("lin_range(g(2),-10,6)", entries.get(1).expression);
        assertEquals("lin_range(g(3),1,500)", entries.get(2).expression);
    }

    @Test
    @DisplayName("An unrecognised parameter is left blank and consumes no gene index")
    void testUnrecognisedParameterLeavesNoGeneIndexGap() {
        // A gap would still optimise correctly — the engine sizes the problem from the
        // unique indices actually referenced — but contiguous indices keep the generated
        // INI readable, so the counter must only advance on success.
        List<ParamEntry> entries = ParametersConfigPanel.buildAutoGeneratedEntries(
                List.of("node.g1.x1", "node.unknown.mystery", "node.g1.x2"));

        assertEquals("lin_range(g(1),1,1500)", entries.get(0).expression);
        assertEquals("", entries.get(1).expression, "unrecognised parameter must be left blank");
        assertEquals("lin_range(g(2),-10,6)", entries.get(2).expression);
    }

    @Test
    @DisplayName("A routing node's parameters are auto-generated, not left blank")
    void testRoutingParametersAreAutoGenerated() {
        List<ParamEntry> nlm = ParametersConfigPanel.buildAutoGeneratedEntries(
                List.of("node.r1.nlm_k", "node.r1.nlm_m"));
        assertEquals("log_range(g(1),100,500000)", nlm.get(0).expression);
        assertEquals("lin_range(g(2),0.5,1)", nlm.get(1).expression);

        List<ParamEntry> pwl = ParametersConfigPanel.buildAutoGeneratedEntries(
                List.of("node.r2.pwl_tt_0", "node.r2.pwl_tt_1"));
        assertEquals("lin_range(g(1),0,5)", pwl.get(0).expression);
        assertEquals("lin_range(g(2),0,5)", pwl.get(1).expression);
    }

    @Test
    @DisplayName("Each auto-generated parameter gets its own gene index")
    void testEachParameterGetsADistinctGeneIndex() {
        List<ParamEntry> entries = ParametersConfigPanel.buildAutoGeneratedEntries(
                List.of("node.sac_a.adimp", "node.sac_b.adimp", "node.r1.nlm_m"));

        // Same parameter on two nodes must not be tied together by default — tying is
        // something the modeller opts into by hand-editing the shared gene index.
        assertNotEquals(entries.get(0).expression, entries.get(1).expression);
        assertEquals("log_range(g(1),1E-05,0.15)", entries.get(0).expression);
        assertEquals("log_range(g(2),1E-05,0.15)", entries.get(1).expression);
        assertEquals("lin_range(g(3),0.5,1)", entries.get(2).expression);
    }
}
