"""Type stubs for the native (PyO3) module."""
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

# pylint: disable=unused-argument

def _read_pixie_raw(path: str) -> Tuple[NDArray[np.int64], Dict[str, NDArray[np.float64]]]: ...
def _write_pixie_raw(
    path: str,
    series_names: List[str],
    timestamps_unix_seconds: NDArray[np.int64],
    values_per_series: List[NDArray[np.float64]],
    use_64bit_precision: bool,
) -> None: ...
def _simulate_from_file(
    model_path: str,
    output_path: Optional[str] = None,
    mass_balance_path: Optional[str] = None,
) -> None: ...
def _optimise_from_file(
    config_path: str,
    model_path: Optional[str] = None,
    save_model_path: Optional[str] = None,
    progress: Optional[Callable[[Dict[str, Any]], Any]] = None,
) -> Dict[str, Any]: ...

class _PatchMode:
    Merge: "_PatchMode"
    Replace: "_PatchMode"
    Delete: "_PatchMode"
    DeleteMissingOk: "_PatchMode"

class _Model:
    def __init__(self) -> None: ...
    def _from_file(self, model_path: str) -> "_Model": ...
    def _from_model_string(self, model_string: str) -> "_Model": ...
    def _run(self) -> "_Model": ...
    def _patch(self, patch_string: str, mode: _PatchMode) -> "_Model": ...
    def _get_outputs(
        self, names: Optional[List[str]] = None
    ) -> Tuple[int, int, int, List[Tuple[str, NDArray[np.float64]]]]: ...
    def _sections(self) -> List[str]: ...
    def _get_section(self, section_name: str) -> Optional[Dict[str, str]]: ...
    def _has_section(self, section_name: str) -> bool: ...
    def _get_property(self, section_name: str, property_name: str) -> str: ...
    def _get_property_by_designation(self, property_designation: str) -> str: ...
    def _to_string(self) -> str: ...
    def _save(self, filename: str) -> "_Model": ...
