[kalix]
start = 2000-01-01
end = 2020-12-31

# ------------------------------------------------------------------------------

# At the start of each water year (July): wipe last year's allocation, then
# announce this year's based on the resource. File order matters — reset runs
# before announce on the shared trigger day.
[ras.reset]
targets = acc.good_luck_wss_mp, acc.good_luck_wss_hp
trigger = start_water_year(6)
action  = reset_allocation

# TODO: check if I can define a var above this, or whether ras get executed before vars

[ras.mp_annoucement]
targets = acc.good_luck_wss_mp
trigger = start_water_year(7)
action  = allocate(table.good_luck_wss_mp_alloc_curve(min(120000, node.paradise_dam.volume[-1, 0])))

[ras.hp_annoucement]
targets = acc.good_luck_wss_hp
trigger = start_water_year(7)
action  = allocate(table.good_luck_wss_hp_alloc_curve(min(120000, node.paradise_dam.volume[-1, 0])))

# ------------------------------------------------------------------------------

[node.in1]
loc = 0, 0
type = inflow
inflow = 100 * (sim.year % 6)
ds_1 = paradise_dam

[node.paradise_dam]
loc = 0.00, 30.00
initial_volume = 120000
type = storage
dimensions = Level [m], Volume [ML], Area [km2], Spill [ML],
             0        , 0          , 0         , 0,
             10       , 120000     , 10        , 0,
             11       , 121000     , 10        , 1e8,
             12       , 122000     , 10        , 1e8,
ds_1 = rum_runner_farming_co

[node.rum_runner_farming_co]
loc = 0.26, 57.91
type = regulated_user
accounts = mp_rrfc
order = 270 #270 * 366 = 98820
ds_1 = soggy_council_tws

[node.soggy_council_tws]
loc = -0.26, 85.17
type = regulated_user
accounts = hp_sgtc
order = 20 #20 * 366 = 7320
ds_1 = eos

[node.eos]
loc = 0.26, 119.62
type = gauge

# ------------------------------------------------------------------------------

[acc.good_luck_wss_mp]
accounts = name   , size,
           mp_rrfc, 98820,

[acc.good_luck_wss_hp]
accounts = name   , size,
           hp_sgtc, 7620,

[table.good_luck_wss_mp_alloc_curve]
values = Volume [ML], Percent,
         0          , 0,
         7650       , 0,
         106440     , 100,
         120000     , 100,

[table.good_luck_wss_hp_alloc_curve]
values = Volume [ML], Percent,
         0          , 100,
         120000     , 100,

# ------------------------------------------------------------------------------

[outputs]
node.in1.ds_1
node.paradise_dam.volume
node.paradise_dam.ds_1
node.paradise_dam.ds_1_outlet
node.paradise_dam.ds_1_spill
node.rum_runner_farming_co.diversion
node.soggy_council_tws.diversion
node.eos.ds_1
acc.mp_rrfc.closing_balance
acc.mp_rrfc.debits
acc.hp_sgtc.closing_balance
#ras.announce.pct
