
# NOTE: The GR4H model is better suited for sub-daily timesteps. This regression test 
#       operates at a daily timestep but still serves as a regression test to flag if 
#       the results ever unexpectedly change.

[kalix]

[inputs]
data.csv

[node.mygr4jnode]
loc = 0, 0
type = gr4j
variant = gr4h
area = 228
rain = data.data_csv.by_name.rain
evap = data.data_csv.by_name.mpot
params = 107.75678222230046, -8, 351.5043426183032, 2.437818339496865

[outputs]
node.mygr4jnode.ds_1
node.mygr4jnode.dsflow
node.mygr4jnode.runoff_volume



