#!/usr/bin/env python3
"""
Generates the synthetic models and climate/flow data for the speed test suite.

The three models each emphasise a different part of the engine's hot path:

  1_sacramento_long   - one Sacramento node over 300 years of daily data.
                        Emphasises raw rainfall-runoff arithmetic.
  2_unregulated_users - parallel river reaches with ~70 unregulated users on
                        plain scalar demands. The CONTROL for model 3: same
                        network, no expressions.
  3_unregulated_users_with_functions - the same reaches and users, but pump
                        capacities and flow thresholds use DynamicInput
                        expressions patterned on real models (laddered max/min
                        shares, node-reference conditionals). The 2-vs-3 gap
                        isolates the cost of expression evaluation.
  4_regulated_system  - three valleys of storages in sequence and parallel,
                        lag+PWL routing, and seasonal regulated users, joining
                        into a common trunk. Emphasises the ordering phase and
                        the storage backward-Euler solver.

Deterministic: fixed seeds, so regenerating produces identical files.
The generated .ini and .csv files are committed; do not hand-edit them —
change this script and regenerate instead.
"""

import math
import random
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).parent


# ---------------------------------------------------------------------------
# Data synthesis
# ---------------------------------------------------------------------------

def daily_dates(start_year, n_years):
    """All daily dates from start_year-01-01 through (start_year+n_years-1)-12-31."""
    start = date(start_year, 1, 1)
    end = date(start_year + n_years - 1, 12, 31)
    days = (end - start).days + 1
    return [start + timedelta(days=i) for i in range(days)]


def synth_climate(dates, rng):
    """Seasonal daily rainfall (mm) and PET (mm). Southern-hemisphere phasing."""
    rain, pet = [], []
    for d in dates:
        doy = d.timetuple().tm_yday
        season = math.sin(2.0 * math.pi * (doy - 15) / 365.25)  # +1 mid-summer
        p_wet = 0.16 + 0.10 * season
        depth = rng.expovariate(1.0 / (6.0 + 4.0 * season)) if rng.random() < p_wet else 0.0
        rain.append(depth)
        pet.append(max(0.5, 5.5 + 3.5 * season + rng.gauss(0.0, 0.4)))
    return rain, pet


def synth_flow(dates, rng, scale):
    """Flow-like series (ML/d): baseflow recession plus rain-driven pulses."""
    q = scale
    out = []
    for d in dates:
        doy = d.timetuple().tm_yday
        season = math.sin(2.0 * math.pi * (doy - 15) / 365.25)
        if rng.random() < 0.10 + 0.06 * season:
            q += rng.expovariate(1.0 / (scale * 4.0))  # storm pulse
        q *= 0.94  # recession
        q += scale * 0.03  # persistent baseflow
        out.append(q)
    return out


def write_csv(path, dates, columns):
    """columns: list of (name, values). Dates formatted YYYY-MM-DD."""
    with open(path, "w", newline="\n") as f:
        f.write("Date," + ",".join(name for name, _ in columns) + "\n")
        for i, d in enumerate(dates):
            row = ",".join(f"{vals[i]:.2f}" for _, vals in columns)
            f.write(f"{d.isoformat()},{row}\n")


# ---------------------------------------------------------------------------
# INI assembly
# ---------------------------------------------------------------------------

class ModelBuilder:
    """Accumulates node sections in definition order (which must be topological:
    Kalix requires every link's upstream node to be defined before its
    downstream node)."""

    def __init__(self, title):
        self.lines = [f"# {title}", "# Generated by generate_models.py - do not hand-edit.", "",
                      "[kalix]", "# Full period", ""]
        self.outputs = []

    def inputs(self, *files):
        self.lines += ["[data]"] + list(files) + [""]

    def node(self, name, node_type, x, y, props):
        self.lines += [f"[node.{name}]", f"loc = {x:.1f}, {y:.1f}", f"type = {node_type}"]
        self.lines += props + [""]

    def output(self, ref):
        self.outputs.append(ref)

    def write(self, path):
        with open(path, "w", newline="\n") as f:
            f.write("\n".join(self.lines))
            f.write("[outputs]\n" + "\n".join(self.outputs) + "\n")


STORAGE_DIMENSIONS = """dimensions = Level [m], Volume [ML], Area [km2], Spill [ML],
             0.0      , 0.0        , 0.0       , 0.0,
             0.5      , {v8:.0f}   , {a4:.3f}  , 0.0,
             1.0      , {vf:.0f}   , {af:.3f}  , 0.0,
             1.0003   , {vf1:.0f}  , {af1:.3f} , 1.0E9,
             100.0    , 1.0E9      , {ax:.1f}  , 1.0E9,"""


def storage_props(full_volume, initial_fraction=0.8, order_through=False):
    area_full = full_volume / 300.0
    dims = STORAGE_DIMENSIONS.format(
        v8=full_volume / 8.0, a4=area_full / 4.0,
        vf=full_volume, af=area_full,
        vf1=full_volume + 1.0, af1=area_full * 1.001,
        ax=area_full * 10.0,
    )
    props = [f"initial_volume = {initial_fraction * full_volume:.0f}"]
    if order_through:
        props.append("order_through = true")
    return props + dims.split("\n")


# ---------------------------------------------------------------------------
# Model 1: long-running single Sacramento node
# ---------------------------------------------------------------------------

# A realistic mid-range parameter set (adapted from the picnic calibration).
SAC_PARAMS = ("0.0004, 295.1, 64.2, 0.0119, 0.183, 80.1, 0.0000208, 0.423, "
              "2.043, 0.0000173, 0.000727, 0.000425, 55.3, 0.488, 12.66, 411.8, 0.947")


def build_model_1():
    folder = HERE / "1_sacramento_long"
    folder.mkdir(exist_ok=True)

    rng = random.Random(101)
    dates = daily_dates(1889, 300)
    rain, pet = synth_climate(dates, rng)
    write_csv(folder / "rain.csv", dates, [("rain_mm", rain)])
    write_csv(folder / "mpot.csv", dates, [("pet_mm", pet)])

    m = ModelBuilder("Speed test 1: single Sacramento node, 300 years daily")
    m.inputs("rain.csv", "mpot.csv")
    m.node("catchment", "sacramento", 0, 0, [
        "area = 228",
        "rain = data.rain_csv.by_index.1",
        "evap = data.mpot_csv.by_index.1",
        f"params = {SAC_PARAMS}",
    ])
    m.output("node.catchment.ds_1")
    m.output("node.catchment.flosf")
    m.output("node.catchment.flobf")
    m.output("node.catchment.floin")
    m.write(folder / "kalix.ini")

    (folder / "bench.json").write_text('{"repeats": 15}\n')


# ---------------------------------------------------------------------------
# Model 2: unregulated users with pump capacity functions
# ---------------------------------------------------------------------------

N_REACHES = 6
USERS_PER_REACH = 12


def pump_props(rng, style, head_gauge):
    """Pump/threshold expressions patterned on real unregulated systems."""
    if style == 0:
        return [f"pump = {rng.uniform(2, 30):.1f}"]
    if style == 1:
        cap = rng.uniform(5, 60)
        thresh = rng.uniform(20, 120)
        return [f"pump = max(0, min({cap:.1f}, this.usflow - {thresh:.0f}))"]
    if style == 2:
        caps = sorted(rng.uniform(2, 80) for _ in range(3))
        threshes = sorted(rng.uniform(20, 1500) for _ in range(3))
        terms = ", ".join(f"min({c:.1f}, this.usflow - {t:.0f})"
                          for c, t in zip(caps, threshes))
        return [f"pump = max(0, {terms})"]
    if style == 3:
        thresh = rng.uniform(50, 200)
        cap = rng.uniform(10, 50)
        return [f"pump = if(node.{head_gauge}.dsflow < {thresh:.0f}, 0, {cap:.1f})"]
    # style 4: constant pump gated by a flow threshold expression
    thresh = rng.uniform(30, 100)
    return [
        f"pump = {rng.uniform(3, 20):.1f}",
        f"flow_threshold = max(0.05 * this.usflow, {thresh:.0f})",
    ]


CONTROL_DEMAND = 18.6  # scalar demand for the no-functions control model


def build_unregulated(folder_name, title, with_functions):
    folder = HERE / folder_name
    folder.mkdir(exist_ok=True)

    rng = random.Random(202)
    dates = daily_dates(1925, 100)
    cols = [(f"inflow_{i + 1}", synth_flow(dates, rng, scale=rng.uniform(20, 80)))
            for i in range(N_REACHES)]
    write_csv(folder / "inflows.csv", dates, cols)

    m = ModelBuilder(title)
    m.inputs("inflows.csv")

    reach_ends = []
    for r in range(N_REACHES):
        x = r * 40.0
        inflow = f"r{r}_inflow"
        gauge = f"r{r}_headgauge"
        m.node(inflow, "inflow", x, 0, [
            f"inflow = data.inflows_csv.by_index.{r + 1}",
            f"ds_1 = {gauge}",
        ])
        prev = gauge
        # First user is defined after the gauge; gauge links to it below.
        first_user = f"r{r}_user0"
        m.node(gauge, "gauge", x, 10, [f"ds_1 = {first_user}"])
        for u in range(USERS_PER_REACH):
            name = f"r{r}_user{u}"
            nxt = f"r{r}_user{u + 1}" if u + 1 < USERS_PER_REACH else f"conf{r // 2}"
            if with_functions:
                props = ["demand = 999999999"]
                props += pump_props(rng, (r * USERS_PER_REACH + u) % 5, gauge)
            else:
                props = [f"demand = {CONTROL_DEMAND}"]
            props += [f"ds_1 = {nxt}"]
            m.node(name, "unregulated_user", x, 20 + u * 10, props)
            prev = name
        reach_ends.append(prev)

    # Pairs of reaches join at confluences, each draining to a gauge+blackhole.
    for c in range(N_REACHES // 2):
        conf = f"conf{c}"
        gauge = f"outlet_gauge{c}"
        m.node(conf, "confluence", c * 80 + 20, 160, [f"ds_1 = {gauge}"])
        m.node(gauge, "gauge", c * 80 + 20, 170, [f"ds_1 = sink{c}"])
        m.node(f"sink{c}", "blackhole", c * 80 + 20, 180, [])
        m.output(f"node.{gauge}.ds_1")

    for r in (0, 3):
        m.output(f"node.r{r}_user5.diversion")
        m.output(f"node.r{r}_user5.ds_1")
    m.write(folder / "kalix.ini")

    (folder / "bench.json").write_text('{"repeats": 7}\n')


def build_model_2():
    build_unregulated(
        "2_unregulated_users",
        "Speed test 2: unregulated users with scalar demands (control for test 3)",
        with_functions=False,
    )


def build_model_3():
    build_unregulated(
        "3_unregulated_users_with_functions",
        "Speed test 3: unregulated users with pump capacity functions",
        with_functions=True,
    )


# ---------------------------------------------------------------------------
# Model 4: heavily regulated system
# ---------------------------------------------------------------------------

def seasonal_order(rng):
    hi = rng.uniform(10, 30)
    lo = rng.uniform(1, 8)
    return f"order = if(sim.month >= 10 || sim.month <= 3, {hi:.1f}, {lo:.1f})"


ROUTING_PWL = """pwl = 0, {t0:.1f},
      50, {t1:.1f},
      500, {t2:.1f},
      100000, {t3:.1f},"""


def routing_props(rng, dest):
    tt = sorted((rng.uniform(0.3, 2.5) for _ in range(4)), reverse=True)
    pwl = ROUTING_PWL.format(t0=tt[0], t1=tt[1], t2=tt[2], t3=tt[3])
    return [f"lag = {rng.choice([0, 1, 1, 2])}"] + pwl.split("\n") + [f"ds_1 = {dest}"]


def build_model_4():
    folder = HERE / "4_regulated_system"
    folder.mkdir(exist_ok=True)

    rng = random.Random(303)
    dates = daily_dates(1925, 100)
    cols = [(f"inflow_{i + 1}", synth_flow(dates, rng, scale=rng.uniform(30, 90)))
            for i in range(6)]
    write_csv(folder / "inflows.csv", dates, cols)

    m = ModelBuilder("Speed test 4: storages in sequence and parallel, routing, regulated users")
    m.inputs("inflows.csv")

    valley_ends = []
    for v in range(3):
        x = v * 60.0
        # Main stem: inflow -> headwater storage -> routing -> 2 users
        m.node(f"v{v}_inflow_a", "inflow", x, 0, [
            f"inflow = data.inflows_csv.by_index.{v * 2 + 1}",
            f"ds_1 = v{v}_headwater_dam",
        ])
        m.node(f"v{v}_headwater_dam", "storage", x, 10,
               storage_props(80_000) + [f"ds_1 = v{v}_route_a"])
        m.node(f"v{v}_route_a", "routing", x, 20, routing_props(rng, f"v{v}_user_a0"))
        m.node(f"v{v}_user_a0", "regulated_user", x, 30,
               [seasonal_order(rng), f"ds_1 = v{v}_user_a1"])
        m.node(f"v{v}_user_a1", "regulated_user", x, 40,
               [seasonal_order(rng), f"ds_1 = v{v}_junction"])

        # Parallel branch: inflow -> storage -> routing, joins main stem
        m.node(f"v{v}_inflow_b", "inflow", x + 20, 0, [
            f"inflow = data.inflows_csv.by_index.{v * 2 + 2}",
            f"ds_1 = v{v}_branch_dam",
        ])
        m.node(f"v{v}_branch_dam", "storage", x + 20, 10,
               storage_props(30_000) + [f"ds_1 = v{v}_route_b"])
        m.node(f"v{v}_route_b", "routing", x + 20, 20, routing_props(rng, f"v{v}_junction"))

        # Junction, then an order-through re-regulating storage and more demand
        m.node(f"v{v}_junction", "confluence", x + 10, 50, [f"ds_1 = v{v}_midstorage"])
        m.node(f"v{v}_midstorage", "storage", x + 10, 60,
               storage_props(15_000, order_through=True) + [f"ds_1 = v{v}_route_c"])
        m.node(f"v{v}_route_c", "routing", x + 10, 70, routing_props(rng, f"v{v}_user_c0"))
        m.node(f"v{v}_user_c0", "regulated_user", x + 10, 80,
               [seasonal_order(rng), f"ds_1 = v{v}_user_c1"])
        m.node(f"v{v}_user_c1", "regulated_user", x + 10, 90,
               [seasonal_order(rng), f"ds_1 = v{v}_gauge"])
        end = f"v{v}_gauge"
        valley_ends.append(end)

    # Valleys 0+1 join, then join valley 2, into a trunk storage and users.
    m.node("v0_gauge", "gauge", 10, 100, ["ds_1 = trunk_conf_a"])
    m.node("v1_gauge", "gauge", 70, 100, ["ds_1 = trunk_conf_a"])
    m.node("trunk_conf_a", "confluence", 40, 110, ["ds_1 = trunk_route_a"])
    m.node("trunk_route_a", "routing", 40, 120, routing_props(rng, "trunk_user_a"))
    m.node("trunk_user_a", "regulated_user", 40, 130,
           [seasonal_order(rng), "ds_1 = trunk_conf_b"])
    m.node("v2_gauge", "gauge", 130, 100, ["ds_1 = trunk_conf_b"])
    m.node("trunk_conf_b", "confluence", 80, 140, ["ds_1 = trunk_dam"])
    m.node("trunk_dam", "storage", 80, 150,
           storage_props(120_000) + ["ds_1 = trunk_route_b"])
    m.node("trunk_route_b", "routing", 80, 160, routing_props(rng, "trunk_user_b0"))
    m.node("trunk_user_b0", "regulated_user", 80, 170,
           [seasonal_order(rng), "ds_1 = trunk_user_b1"])
    m.node("trunk_user_b1", "regulated_user", 80, 180,
           [seasonal_order(rng), "ds_1 = trunk_user_b2"])
    m.node("trunk_user_b2", "regulated_user", 80, 190,
           [seasonal_order(rng), "ds_1 = outlet_gauge"])
    m.node("outlet_gauge", "gauge", 80, 200, ["ds_1 = sink"])
    m.node("sink", "blackhole", 80, 210, [])

    m.output("node.outlet_gauge.ds_1")
    for v in range(3):
        m.output(f"node.v{v}_headwater_dam.volume")
        m.output(f"node.v{v}_midstorage.volume")
        m.output(f"node.v{v}_user_c0.diversion")
    m.output("node.trunk_dam.volume")
    m.write(folder / "kalix.ini")

    (folder / "bench.json").write_text('{"repeats": 7}\n')


# ---------------------------------------------------------------------------
# Model 5: ordering-heavy network (confluence density and node-array size)
# ---------------------------------------------------------------------------

# Shaped on the topology of a real regulated valley model: ~110 nodes, ten
# confluences, and a long ordering chain through storages, order controls, a
# splitter diamond and a loss. Model 4 is the closest sibling but has five
# confluences (all in legacy bare mode) and about half the nodes, so it can
# see neither the per-confluence ordering cost nor the cache pressure that a
# large NodeEnum array puts on per-node struct size -- the effect behind the
# 2026-08 ConfluenceNode field-order regression (manifestos/performance.md
# 3.4). All three confluence ordering modes appear here: bare/legacy, a
# single `regulated` name (all orders up one pathway), and two `regulated`
# names split by harmony_fraction, which no other speed model exercises.
#
# Synthetic throughout: the topology is modelled on a real system, none of
# its names, parameters or data are used.

def build_model_5():
    folder = HERE / "5_ordering_confluences"
    folder.mkdir(exist_ok=True)

    rng = random.Random(505)
    dates = daily_dates(1890, 130)
    cols = [(f"inflow_{i + 1}", synth_flow(dates, rng, scale=rng.uniform(20, 80)))
            for i in range(10)]
    write_csv(folder / "inflows.csv", dates, cols)

    m = ModelBuilder("Speed test 5: ordering through a cascade of confluences")
    m.inputs("inflows.csv")

    def reach(prefix, n, x, y0, dest):
        """A chain of n reporting gauges ending at dest. Real valley models
        carry many of these; they are cheap per step but they are what makes
        the node array big."""
        for k in range(n):
            nxt = dest if k == n - 1 else f"{prefix}_g{k + 1}"
            m.node(f"{prefix}_g{k}", "gauge", x, y0 + k * 4, [f"ds_1 = {nxt}"])

    # --- Eight headwater tributaries -------------------------------------
    # The first five are storage-regulated, so orders propagate up through a
    # dam; the rest are unregulated headwaters that only pass flow.
    for t in range(8):
        x = t * 25.0
        m.node(f"t{t}_inflow", "inflow", x, 0, [
            f"inflow = data.inflows_csv.by_index.{t + 1}",
            f"ds_1 = t{t}_head",
        ])
        if t < 5:
            m.node(f"t{t}_head", "storage", x, 10,
                   storage_props(40_000 + t * 5_000) + [f"ds_1 = t{t}_route"])
            m.node(f"t{t}_route", "routing", x, 20, routing_props(rng, f"t{t}_ureg"))
        else:
            m.node(f"t{t}_head", "gauge", x, 10, [f"ds_1 = t{t}_route"])
            m.node(f"t{t}_route", "gauge", x, 20, [f"ds_1 = t{t}_ureg"])
        m.node(f"t{t}_ureg", "unregulated_user", x, 30, [
            f"demand = {rng.uniform(2, 9):.1f}",
            f"ds_1 = t{t}_g0",
        ])
        reach(f"t{t}", 3, x, 40, f"c0{t // 2}")

    # --- Merge cascade: 8 tributaries -> 4 -> 2 -> 1 ----------------------
    # Each level mixes the confluence ordering modes on purpose.
    m.node("c00", "confluence", 12, 60, ["ds_1 = c10"])                    # bare
    m.node("c01", "confluence", 62, 60, [                                  # one name
        "regulated = t2_g2", "ds_1 = c10"])
    m.node("c02", "confluence", 112, 60, [                                 # two names
        "regulated = t4_g2, t5_g2",
        "harmony_fraction = if(sim.month >= 10 || sim.month <= 3, 0.7, 0.35)",
        "ds_1 = c11"])
    m.node("c03", "confluence", 162, 60, ["ds_1 = c11"])                   # bare

    m.node("c10", "confluence", 37, 75, ["regulated = c00", "ds_1 = c20"])
    m.node("c11", "confluence", 137, 75, ["harmony_fraction = 0.4", "ds_1 = c20"])

    m.node("c20", "confluence", 87, 90, [
        "regulated = c10, c11",
        "harmony_fraction = if(sim.month >= 10 || sim.month <= 3, 0.6, 0.45)",
        "ds_1 = trunk_oc0"])

    # --- Trunk: order control, routing, regulated demand ------------------
    m.node("trunk_oc0", "order_control", 87, 100, ["max_order = 900", "ds_1 = trunk_route"])
    m.node("trunk_route", "routing", 87, 110, routing_props(rng, "trunk_u0"))
    for u in range(5):
        nxt = f"trunk_u{u + 1}" if u < 4 else "trunk_split"
        m.node(f"trunk_u{u}", "regulated_user", 87, 120 + u * 6,
               [seasonal_order(rng), f"ds_1 = {nxt}"])

    # --- Splitter diamond, rejoining at a confluence ----------------------
    m.node("trunk_split", "splitter", 87, 155, [
        "table = 0, 0,",
        "        400, 120,",
        "        100000, 120,",
        "ds_1 = a_g0", "ds_2 = b_g0"])
    reach("a", 4, 67, 165, "a_loss")
    m.node("a_loss", "loss", 67, 185, [
        "table = 0, 0,",
        "        60, 12,",
        "        400, 30,",
        "        999999, 30,",
        "ds_1 = c30"])
    reach("b", 4, 107, 165, "c30")
    m.node("c30", "confluence", 87, 195, ["ds_1 = trunk_oc1"])

    # --- Lower trunk, with two side tributaries joining -------------------
    m.node("trunk_oc1", "order_control", 87, 205, ["min_order = 5", "ds_1 = trunk_g0"])
    reach("trunk", 5, 87, 215, "c31")

    m.node("s0_inflow", "inflow", 150, 205, [
        "inflow = data.inflows_csv.by_index.9", "ds_1 = s0_ureg"])
    m.node("s0_ureg", "unregulated_user", 150, 212,
           [f"demand = {rng.uniform(2, 9):.1f}", "ds_1 = s0_g0"])
    reach("s0", 3, 150, 220, "c31")
    m.node("c31", "confluence", 118, 240, ["regulated = trunk_g4", "ds_1 = trunk_u5"])

    for u in range(5, 10):
        nxt = f"trunk_u{u + 1}" if u < 9 else "c32"
        m.node(f"trunk_u{u}", "regulated_user", 118, 250 + (u - 5) * 6,
               [seasonal_order(rng), f"ds_1 = {nxt}"])

    m.node("s1_inflow", "inflow", 180, 250, [
        "inflow = data.inflows_csv.by_index.10", "ds_1 = s1_ureg"])
    m.node("s1_ureg", "unregulated_user", 180, 257,
           [f"demand = {rng.uniform(2, 9):.1f}", "ds_1 = s1_g0"])
    reach("s1", 3, 180, 265, "c32")
    m.node("c32", "confluence", 148, 285, ["ds_1 = outlet_g0"])

    reach("outlet", 2, 148, 295, "sink")
    m.node("sink", "blackhole", 148, 310, [])

    m.output("node.outlet_g1.ds_1")
    m.output("node.c20.ds_1_order")
    m.output("node.c20.harmony_fraction")
    for t in range(5):
        m.output(f"node.t{t}_head.volume")
    m.write(folder / "kalix.ini")

    (folder / "bench.json").write_text('{"repeats": 5}\n')


if __name__ == "__main__":
    build_model_1()
    build_model_2()
    build_model_3()
    build_model_4()
    build_model_5()
    print("Generated speed test models 1-5.")
